## Tokenization

In [8]:
!pip install nltk

In [12]:
corpus = '"Hey! How are you doing today?" asked John.'
print(corpus)

"Hey! How are you doing today?" asked John.


In [16]:
# Tokenization
# sentance--> Paragrahps
from nltk.tokenize import sent_tokenize

In [20]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [21]:
documents = sent_tokenize(corpus)

In [24]:
type(documents)

list

In [28]:
for sentance in documents:
    print(sentance)

"Hey!
How are you doing today?"
asked John.


In [30]:
# Tokenization
# paeragraphs --> words
# sentance --> words
from nltk.tokenize import word_tokenize

In [32]:
word_tokenize(corpus)

['``',
 'Hey',
 '!',
 'How',
 'are',
 'you',
 'doing',
 'today',
 '?',
 "''",
 'asked',
 'John',
 '.']

In [34]:
for sentance in documents:
    print(word_tokenize(sentance))

['``', 'Hey', '!']
['How', 'are', 'you', 'doing', 'today', '?', "''"]
['asked', 'John', '.']


In [38]:
from nltk.tokenize import wordpunct_tokenize

In [40]:
wordpunct_tokenize(corpus)

['"',
 'Hey',
 '!',
 'How',
 'are',
 'you',
 'doing',
 'today',
 '?"',
 'asked',
 'John',
 '.']

In [42]:
from nltk.tokenize import TreebankWordTokenizer

In [44]:
Tokenizer = TreebankWordTokenizer()

In [46]:
Tokenizer.tokenize(corpus)

['``',
 'Hey',
 '!',
 'How',
 'are',
 'you',
 'doing',
 'today',
 '?',
 "''",
 'asked',
 'John',
 '.']

# Stopword

In [155]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them."""

In [157]:
from nltk.stem import PorterStemmer

In [171]:
stemmer = PorterStemmer()

In [161]:
from nltk.corpus import stopwords

In [163]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [165]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [169]:
sentences = nltk.sent_tokenize(paragraph)

In [173]:
sentences

['I have three visions for India.',
 'In 3000 years of our history, people from all over \n               the world have come and invaded us, captured our lands, conquered our minds.',
 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.',
 'Yet we have not done this to any other nation.',
 'We have not conquered anyone.',
 'We have not grabbed their land, their culture, \n               their history and tried to enforce our way of life on them.']

In [187]:
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [stemmer.stem(word) for word in words if word not in set(stopwords.words("english"))]
    sentences[i] = ' '.join(words)

In [189]:
sentences

['i three vision india .',
 'in 3000 year histori , peopl world come invad us , captur land , conquer mind .',
 'from alexand onward , greek , turk , mogul , portugues , british , french , dutch , came loot us , took .',
 'yet done nation .',
 'we conquer anyon .',
 'we grab land , cultur , histori tri enforc way life .']

In [193]:
from nltk.stem import SnowballStemmer
snowballstemmer=SnowballStemmer('english')

In [195]:
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [snowballstemmer.stem(word) for word in words if word not in set(stopwords.words("english"))]
    sentences[i] = ' '.join(words)

In [197]:
sentences

['three vision india .',
 '3000 year histori , peopl world come invad us , captur land , conquer mind .',
 'alexand onward , greek , turk , mogul , portugu , british , french , dutch , came loot us , took .',
 'yet done nation .',
 'conquer anyon .',
 'grab land , cultur , histori tri enforc way life .']

In [203]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [199]:
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [lemmatizer.lemmatize(word.lower(),pos='v') for word in words if word not in set(stopwords.words("english"))]
    sentences[i] = ' '.join(words)

In [201]:
sentences

['three vision india .',
 '3000 year histori , peopl world come invad us , captur land , conquer mind .',
 'alexand onward , greek , turk , mogul , portugu , british , french , dutch , come loot us , take .',
 'yet do nation .',
 'conquer anyon .',
 'grab land , cultur , histori tri enforc way life .']

# Stemming

In [51]:
## Classification Problem
## Comments of product is a positive review or negative review
## Reviews----> eating, eat,eaten [going,gone,goes]--->go

words=["eating","eats","eaten","writing","writes","programming","programs","history","finally","finalized"]

# PorterStemmer

In [56]:
from nltk.stem import PorterStemmer

In [62]:
stemming = PorterStemmer()

In [66]:
for word in words:
    print(word+"---->"+stemming.stem(word))

eating---->eat
eats---->eat
eaten---->eaten
writing---->write
writes---->write
programming---->program
programs---->program
history---->histori
finally---->final
finalized---->final


In [68]:
stemming.stem("congartualtion")

'congartualt'

In [70]:
stemming.stem("sitting")

'sit'

# RegexpStemmer class

In [73]:
from nltk.stem import RegexpStemmer

In [75]:
reg_stemmer=RegexpStemmer('ing$|s$|e$|able$', min=4)

In [77]:
reg_stemmer.stem("eating")

'eat'

In [79]:
reg_stemmer.stem("ingeating")

'ingeat'

# Snowball Stemmer
   it is a better version of the Porter Stemmer since some issues of it were fixed in this stemmer.

In [84]:
from nltk.stem import SnowballStemmer

In [86]:
snowballsstemmer=SnowballStemmer('english')

In [88]:
for word in words:
    print(word+"---->"+snowballsstemmer.stem(word))

eating---->eat
eats---->eat
eaten---->eaten
writing---->write
writes---->write
programming---->program
programs---->program
history---->histori
finally---->final
finalized---->final


In [90]:
stemming.stem("fairly"),stemming.stem("sportingly")

('fairli', 'sportingli')

In [92]:
snowballsstemmer.stem("fairly"),snowballsstemmer.stem("sportingly")

('fair', 'sport')

# Lemmatization
  it is the process of reducing the words to their base or dictionary form is known as lemma

In [97]:
from nltk.stem import WordNetLemmatizer

In [99]:
lemmatizer=WordNetLemmatizer()

In [103]:
import nltk
nltk.download('wordnet')


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...


True

In [104]:
'''
POS- Noun-n
verb-v
adjective-a
adverb-r
'''
lemmatizer.lemmatize("going",pos='v')

'go'

In [111]:
words=["eating","eats","eaten","writing","writes","programming","programs","history","finally","finalized"]

In [113]:
for word in words:
    print(word+"--->"+lemmatizer.lemmatize(word,pos='v'))

eating--->eat
eats--->eat
eaten--->eat
writing--->write
writes--->write
programming--->program
programs--->program
history--->history
finally--->finally
finalized--->finalize


In [115]:
lemmatizer.lemmatize("fairly",pos='v'),lemmatizer.lemmatize("sportingly")

('fairly', 'sportingly')

# Part of Speech

In [120]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them."""

In [122]:
from nltk.corpus import stopwords
sentences=nltk.sent_tokenize(paragraph)

In [124]:
sentences

['I have three visions for India.',
 'In 3000 years of our history, people from all over \n               the world have come and invaded us, captured our lands, conquered our minds.',
 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.',
 'Yet we have not done this to any other nation.',
 'We have not conquered anyone.',
 'We have not grabbed their land, their culture, \n               their history and tried to enforce our way of life on them.']

In [3]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [142]:
 import nltk
 nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.


True

In [143]:
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [word for word in words if word not in set(stopwords.words('english'))]
    pos_tag=nltk.pos_tag(words)
    print(pos_tag)

[('I', 'PRP'), ('three', 'CD'), ('visions', 'NNS'), ('India', 'NNP'), ('.', '.')]
[('In', 'IN'), ('3000', 'CD'), ('years', 'NNS'), ('history', 'NN'), (',', ','), ('people', 'NNS'), ('world', 'NN'), ('come', 'VBP'), ('invaded', 'VBN'), ('us', 'PRP'), (',', ','), ('captured', 'VBD'), ('lands', 'NNS'), (',', ','), ('conquered', 'VBD'), ('minds', 'NNS'), ('.', '.')]
[('From', 'IN'), ('Alexander', 'NNP'), ('onwards', 'NNS'), (',', ','), ('Greeks', 'NNP'), (',', ','), ('Turks', 'NNP'), (',', ','), ('Moguls', 'NNP'), (',', ','), ('Portuguese', 'NNP'), (',', ','), ('British', 'NNP'), (',', ','), ('French', 'NNP'), (',', ','), ('Dutch', 'NNP'), (',', ','), ('came', 'VBD'), ('looted', 'JJ'), ('us', 'PRP'), (',', ','), ('took', 'VBD'), ('.', '.')]
[('Yet', 'RB'), ('done', 'VBN'), ('nation', 'NN'), ('.', '.')]
[('We', 'PRP'), ('conquered', 'VBD'), ('anyone', 'NN'), ('.', '.')]
[('We', 'PRP'), ('grabbed', 'VBD'), ('land', 'NN'), (',', ','), ('culture', 'NN'), (',', ','), ('history', 'NN'), ('tried'

In [146]:
 "Taj Mahal is a beautiful Monument".split()

['Taj', 'Mahal', 'is', 'a', 'beautiful', 'Monument']

In [150]:
print(nltk.pos_tag("Taj Mahal is a beautiful Monument".split()))

[('Taj', 'NNP'), ('Mahal', 'NNP'), ('is', 'VBZ'), ('a', 'DT'), ('beautiful', 'JJ'), ('Monument', 'NN')]


# Bag of words

In [57]:
import nltk
import re
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
nltk.download('punkt')
import pandas as pd

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [34]:
text = """Natural Language Processing (NLP) is a branch of Artificial Intelligence.
It helps machines understand, interpret, and generate human language.
Applications of NLP include chatbots, translators, and search engines.
Python is widely used for NLP tasks."""

In [36]:
dataset = nltk.sent_tokenize(text)
for i in range(len(dataset)):
     dataset[i] = dataset[i].lower()
     dataset[i] = re.sub(r'\W', ' ', dataset[i])
     dataset[i] = re.sub(r'\s+', ' ', dataset[i])

In [38]:
dataset

['natural language processing nlp is a branch of artificial intelligence ',
 'it helps machines understand interpret and generate human language ',
 'applications of nlp include chatbots translators and search engines ',
 'python is widely used for nlp tasks ']

In [44]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(dataset)

In [46]:
print("Bag of Words Matrix:")
print(X.toarray())

Bag of Words Matrix:
[[0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 1 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0]
 [1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 1]]


In [48]:
print("\nVocabulary (Features):")
print(vectorizer.get_feature_names_out())


Vocabulary (Features):
['and' 'applications' 'artificial' 'branch' 'chatbots' 'engines' 'for'
 'generate' 'helps' 'human' 'include' 'intelligence' 'interpret' 'is' 'it'
 'language' 'machines' 'natural' 'nlp' 'of' 'processing' 'python' 'search'
 'tasks' 'translators' 'understand' 'used' 'widely']


# TF -IDF

TF(t,d) = number of times term t occure in documents/ total number of terms in documents  d

IDF(t,D) = log (total number of documents in corpus D / number of documents containin term t)

In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [53]:
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(dataset)

In [59]:
df_tfidf = pd.DataFrame(X_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

In [61]:
print("TF-IDF Matrix:")
print(df_tfidf)

TF-IDF Matrix:
        and  applications  artificial    branch  chatbots   engines       for  \
0  0.000000      0.000000    0.370824  0.370824  0.000000  0.000000  0.000000   
1  0.274603      0.000000    0.000000  0.000000  0.000000  0.000000  0.000000   
2  0.285040      0.361537    0.000000  0.000000  0.361537  0.361537  0.000000   
3  0.000000      0.000000    0.000000  0.000000  0.000000  0.000000  0.407265   

   generate     helps     human  ...       nlp        of  processing  \
0  0.000000  0.000000  0.000000  ...  0.236692  0.292362    0.370824   
1  0.348299  0.348299  0.348299  ...  0.000000  0.000000    0.000000   
2  0.000000  0.000000  0.000000  ...  0.230764  0.285040    0.000000   
3  0.000000  0.000000  0.000000  ...  0.259952  0.000000    0.000000   

     python    search     tasks  translators  understand      used    widely  
0  0.000000  0.000000  0.000000     0.000000    0.000000  0.000000  0.000000  
1  0.000000  0.000000  0.000000     0.000000    0.348299  0.

# Named Entity Recognaziation

In [9]:
sentence="The Eiffel Tower was built from 1887 to 1889 by Gustave Eiffel, whose company specialized in building metal frameworks and structures."

In [11]:
import nltk
words = nltk.word_tokenize(sentence)
words

['The',
 'Eiffel',
 'Tower',
 'was',
 'built',
 'from',
 '1887',
 'to',
 '1889',
 'by',
 'Gustave',
 'Eiffel',
 ',',
 'whose',
 'company',
 'specialized',
 'in',
 'building',
 'metal',
 'frameworks',
 'and',
 'structures',
 '.']

In [13]:
tag_element = nltk.pos_tag(words)
tag_element

[('The', 'DT'),
 ('Eiffel', 'NNP'),
 ('Tower', 'NNP'),
 ('was', 'VBD'),
 ('built', 'VBN'),
 ('from', 'IN'),
 ('1887', 'CD'),
 ('to', 'TO'),
 ('1889', 'CD'),
 ('by', 'IN'),
 ('Gustave', 'NNP'),
 ('Eiffel', 'NNP'),
 (',', ','),
 ('whose', 'WP$'),
 ('company', 'NN'),
 ('specialized', 'VBD'),
 ('in', 'IN'),
 ('building', 'NN'),
 ('metal', 'NN'),
 ('frameworks', 'NNS'),
 ('and', 'CC'),
 ('structures', 'NNS'),
 ('.', '.')]

In [15]:
nltk.download('maxent_ne_chunker')

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!


True

In [17]:
nltk.download('words')

[nltk_data] Downloading package words to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!


True

In [19]:
nltk.ne_chunk(tag_element).draw()